"""add venue capacity

Revision ID: 35da84470ec7
Revises: ba961fe5b2ab
Create Date: 2026-08-13 19:51:22.449942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35da84470ec7'
down_revision: Union[str, Sequence[str], None] = 'ba961fe5b2ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'capacity')
    # ### end Alembic commands ###
