"""events core table

Revision ID: 3e83e917beec
Revises: d1957a5e2235
Create Date: 2026-08-05 15:36:39.597110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e83e917beec'
down_revision: Union[str, Sequence[str], None] = 'd1957a5e2235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('doors_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='scheduled', nullable=False),
    sa.Column('lineup_complete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('headliner_artist_id', sa.Uuid(), nullable=True),
    sa.Column('venue_id', sa.Uuid(), nullable=True),
    sa.Column('price_from_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_from_currency', sa.String(length=3), nullable=True),
    sa.Column('mxs', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('mxs_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('last_verified', sa.Date(), nullable=True),
    sa.Column('merged_into', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['headliner_artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['merged_into'], ['events.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
