"""notifications and referrals

Revision ID: 50f5ca3c206a
Revises: 6b64794c9038
Create Date: 2026-08-05 17:15:41.375791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f5ca3c206a'
down_revision: Union[str, Sequence[str], None] = '6b64794c9038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_prefs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('on_sale', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('new_show', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('reminder', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('price_drop', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('bucket_list_live', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('trip_cancellation', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('artist_id', sa.Uuid(), nullable=True),
    sa.Column('priority', sa.String(), server_default='normal', nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('partner', sa.String(), nullable=False),
    sa.Column('click_id', sa.String(), nullable=True),
    sa.Column('deep_link', sa.Text(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('converted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referrals')
    op.drop_table('notifications')
    op.drop_table('notification_prefs')
    # ### end Alembic commands ###
