"""festivals family: festivals genres lineup offers sources

Revision ID: 9f483826e2ee
Revises: 8c1f712caed9
Create Date: 2026-08-05 16:49:12.997163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f483826e2ee'
down_revision: Union[str, Sequence[str], None] = '8c1f712caed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('festivals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('city_id', sa.Uuid(), nullable=True),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('artists_count', sa.Integer(), nullable=True),
    sa.Column('lineup_complete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('price_from_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_from_currency', sa.String(length=3), nullable=True),
    sa.Column('mxs', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('mxs_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('last_verified', sa.Date(), nullable=True),
    sa.Column('merged_into', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['merged_into'], ['festivals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('festival_genres',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('festival_id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('festival_id', 'genre_id', name='uq_festival_genre')
    )
    op.create_table('festival_lineup',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('festival_id', sa.Uuid(), nullable=False),
    sa.Column('artist_id', sa.Uuid(), nullable=False),
    sa.Column('day_label', sa.String(), nullable=True),
    sa.Column('is_headliner', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('festival_offers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('festival_id', sa.Uuid(), nullable=False),
    sa.Column('seller_name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('is_official', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_face_value_resale', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('festival_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('festival_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_festival_id', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festivals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_festival_id', name='uq_festival_source')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('festival_sources')
    op.drop_table('festival_offers')
    op.drop_table('festival_lineup')
    op.drop_table('festival_genres')
    op.drop_table('festivals')
    # ### end Alembic commands ###
