"""add artist bio

Revision ID: ba961fe5b2ab
Revises: 46cf3973843b
Create Date: 2026-08-12 14:34:17.058131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba961fe5b2ab'
down_revision: Union[str, Sequence[str], None] = '46cf3973843b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('artists', sa.Column('bio_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'bio_source')
    op.drop_column('artists', 'bio')
    # ### end Alembic commands ###
